import type { ExerciseKind, MuscleGroup } from './programGenerator'

export type LibraryExercise = {
  name: string
  muscleGroup: MuscleGroup
  kind: ExerciseKind
}

// A large, static browsing/search library for the exercise picker — distinct
// from programGenerator's EXERCISE_CATALOG (which drives template
// generation via equipment-tier substitution). Each entry is one fixed name,
// no equipment variants (see design doc). `kind` only decides the default
// rep-range/RIR applied when an entry is picked for the first time (see
// defaultTargetsForKind) — not a rigorous biomechanical classification.
export const EXERCISE_LIBRARY: LibraryExercise[] = [
  // Chest
  { name: 'Barbell Bench Press', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Dumbbell Bench Press', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Incline Barbell Bench Press', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Incline Dumbbell Bench Press', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Decline Bench Press', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Dumbbell Fly', muscleGroup: 'chest', kind: 'isolation' },
  { name: 'Cable Fly', muscleGroup: 'chest', kind: 'isolation' },
  { name: 'Pec Deck Machine', muscleGroup: 'chest', kind: 'isolation' },
  { name: 'Push-up', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Incline Push-up', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Decline Push-up', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Chest Dip', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Machine Chest Press', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Cable Crossover', muscleGroup: 'chest', kind: 'isolation' },
  { name: 'Landmine Press', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Svend Press', muscleGroup: 'chest', kind: 'isolation' },
  { name: 'Guillotine Press', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Smith Machine Bench Press', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Resistance Band Chest Press', muscleGroup: 'chest', kind: 'compound' },
  { name: 'Weighted Dip', muscleGroup: 'chest', kind: 'compound' },

  // Back
  { name: 'Deadlift', muscleGroup: 'back', kind: 'compound' },
  { name: 'Barbell Row', muscleGroup: 'back', kind: 'compound' },
  { name: 'Dumbbell Row', muscleGroup: 'back', kind: 'compound' },
  { name: 'Pull-up', muscleGroup: 'back', kind: 'compound' },
  { name: 'Chin-up', muscleGroup: 'back', kind: 'compound' },
  { name: 'Lat Pulldown', muscleGroup: 'back', kind: 'isolation' },
  { name: 'Seated Cable Row', muscleGroup: 'back', kind: 'compound' },
  { name: 'T-Bar Row', muscleGroup: 'back', kind: 'compound' },
  { name: 'Single-Arm Dumbbell Row', muscleGroup: 'back', kind: 'compound' },
  { name: 'Face Pull', muscleGroup: 'back', kind: 'isolation' },
  { name: 'Straight-Arm Pulldown', muscleGroup: 'back', kind: 'isolation' },
  { name: 'Inverted Row', muscleGroup: 'back', kind: 'compound' },
  { name: 'Rack Pull', muscleGroup: 'back', kind: 'compound' },
  { name: 'Pendlay Row', muscleGroup: 'back', kind: 'compound' },
  { name: 'Hyperextension', muscleGroup: 'back', kind: 'isolation' },
  { name: 'Cable Row Machine', muscleGroup: 'back', kind: 'compound' },
  { name: 'Meadows Row', muscleGroup: 'back', kind: 'compound' },
  { name: 'Renegade Row', muscleGroup: 'back', kind: 'compound' },
  { name: 'Landmine Row', muscleGroup: 'back', kind: 'compound' },
  { name: 'Band Pull-Apart', muscleGroup: 'back', kind: 'isolation' },

  // Shoulders
  { name: 'Overhead Press', muscleGroup: 'shoulders', kind: 'compound' },
  { name: 'Dumbbell Shoulder Press', muscleGroup: 'shoulders', kind: 'compound' },
  { name: 'Arnold Press', muscleGroup: 'shoulders', kind: 'compound' },
  { name: 'Lateral Raise', muscleGroup: 'shoulders', kind: 'isolation' },
  { name: 'Front Raise', muscleGroup: 'shoulders', kind: 'isolation' },
  { name: 'Rear Delt Fly', muscleGroup: 'shoulders', kind: 'isolation' },
  { name: 'Cable Lateral Raise', muscleGroup: 'shoulders', kind: 'isolation' },
  { name: 'Upright Row', muscleGroup: 'shoulders', kind: 'compound' },
  { name: 'Machine Shoulder Press', muscleGroup: 'shoulders', kind: 'compound' },
  { name: 'Push Press', muscleGroup: 'shoulders', kind: 'compound' },
  { name: 'Pike Push-up', muscleGroup: 'shoulders', kind: 'compound' },
  { name: 'Reverse Pec Deck', muscleGroup: 'shoulders', kind: 'isolation' },
  { name: 'Barbell Shrug', muscleGroup: 'shoulders', kind: 'isolation' },
  { name: 'Dumbbell Shrug', muscleGroup: 'shoulders', kind: 'isolation' },
  { name: 'Cable Front Raise', muscleGroup: 'shoulders', kind: 'isolation' },
  { name: 'Seated Dumbbell Press', muscleGroup: 'shoulders', kind: 'compound' },
  { name: 'Bus Driver', muscleGroup: 'shoulders', kind: 'isolation' },
  { name: 'Egyptian Lateral Raise', muscleGroup: 'shoulders', kind: 'isolation' },

  // Biceps
  { name: 'Barbell Curl', muscleGroup: 'biceps', kind: 'compound' },
  { name: 'Dumbbell Curl', muscleGroup: 'biceps', kind: 'compound' },
  { name: 'Hammer Curl', muscleGroup: 'biceps', kind: 'isolation' },
  { name: 'Preacher Curl', muscleGroup: 'biceps', kind: 'isolation' },
  { name: 'Concentration Curl', muscleGroup: 'biceps', kind: 'isolation' },
  { name: 'Cable Curl', muscleGroup: 'biceps', kind: 'isolation' },
  { name: 'Incline Dumbbell Curl', muscleGroup: 'biceps', kind: 'isolation' },
  { name: 'EZ-Bar Curl', muscleGroup: 'biceps', kind: 'compound' },
  { name: 'Spider Curl', muscleGroup: 'biceps', kind: 'isolation' },
  { name: 'Reverse Curl', muscleGroup: 'biceps', kind: 'isolation' },
  { name: 'Zottman Curl', muscleGroup: 'biceps', kind: 'isolation' },
  { name: 'Drag Curl', muscleGroup: 'biceps', kind: 'isolation' },
  { name: 'Cross-Body Hammer Curl', muscleGroup: 'biceps', kind: 'isolation' },
  { name: 'Waiter Curl', muscleGroup: 'biceps', kind: 'isolation' },

  // Triceps
  { name: 'Triceps Pushdown', muscleGroup: 'triceps', kind: 'isolation' },
  { name: 'Overhead Triceps Extension', muscleGroup: 'triceps', kind: 'isolation' },
  { name: 'Skull Crusher', muscleGroup: 'triceps', kind: 'isolation' },
  { name: 'Close-Grip Bench Press', muscleGroup: 'triceps', kind: 'compound' },
  { name: 'Bench Dip', muscleGroup: 'triceps', kind: 'compound' },
  { name: 'Triceps Dip', muscleGroup: 'triceps', kind: 'compound' },
  { name: 'Cable Overhead Extension', muscleGroup: 'triceps', kind: 'isolation' },
  { name: 'Diamond Push-up', muscleGroup: 'triceps', kind: 'compound' },
  { name: 'Triceps Kickback', muscleGroup: 'triceps', kind: 'isolation' },
  { name: 'Single-Arm Pushdown', muscleGroup: 'triceps', kind: 'isolation' },
  { name: 'JM Press', muscleGroup: 'triceps', kind: 'compound' },
  { name: 'Tate Press', muscleGroup: 'triceps', kind: 'isolation' },
  { name: 'Rope Pushdown', muscleGroup: 'triceps', kind: 'isolation' },
  { name: 'Floor Press', muscleGroup: 'triceps', kind: 'compound' },

  // Quads
  { name: 'Back Squat', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Front Squat', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Goblet Squat', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Leg Press', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Bulgarian Split Squat', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Walking Lunge', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Leg Extension', muscleGroup: 'quads', kind: 'isolation' },
  { name: 'Hack Squat', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Step-up', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Sissy Squat', muscleGroup: 'quads', kind: 'isolation' },
  { name: 'Box Squat', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Wall Sit', muscleGroup: 'quads', kind: 'isolation' },
  { name: 'Zercher Squat', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Pistol Squat', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Single-Leg Leg Press', muscleGroup: 'quads', kind: 'compound' },
  { name: 'Smith Machine Squat', muscleGroup: 'quads', kind: 'compound' },

  // Hamstrings
  { name: 'Romanian Deadlift', muscleGroup: 'hamstrings', kind: 'compound' },
  { name: 'Stiff-Leg Deadlift', muscleGroup: 'hamstrings', kind: 'compound' },
  { name: 'Leg Curl', muscleGroup: 'hamstrings', kind: 'isolation' },
  { name: 'Nordic Curl', muscleGroup: 'hamstrings', kind: 'isolation' },
  { name: 'Good Morning', muscleGroup: 'hamstrings', kind: 'compound' },
  { name: 'Single-Leg Romanian Deadlift', muscleGroup: 'hamstrings', kind: 'compound' },
  { name: 'Glute-Ham Raise', muscleGroup: 'hamstrings', kind: 'compound' },
  { name: 'Cable Pull-Through', muscleGroup: 'hamstrings', kind: 'compound' },
  { name: 'Seated Leg Curl', muscleGroup: 'hamstrings', kind: 'isolation' },
  { name: 'Kettlebell Swing', muscleGroup: 'hamstrings', kind: 'compound' },
  { name: 'Cable Leg Curl', muscleGroup: 'hamstrings', kind: 'isolation' },
  { name: 'Sled Leg Curl', muscleGroup: 'hamstrings', kind: 'isolation' },
  { name: 'Banded Leg Curl', muscleGroup: 'hamstrings', kind: 'isolation' },
  { name: 'Deficit Deadlift', muscleGroup: 'hamstrings', kind: 'compound' },

  // Glutes
  { name: 'Hip Thrust', muscleGroup: 'glutes', kind: 'compound' },
  { name: 'Glute Bridge', muscleGroup: 'glutes', kind: 'compound' },
  { name: 'Cable Glute Kickback', muscleGroup: 'glutes', kind: 'isolation' },
  { name: 'Hip Abduction Machine', muscleGroup: 'glutes', kind: 'isolation' },
  { name: 'Curtsy Lunge', muscleGroup: 'glutes', kind: 'compound' },
  { name: 'Sumo Deadlift', muscleGroup: 'glutes', kind: 'compound' },
  { name: 'Single-Leg Hip Thrust', muscleGroup: 'glutes', kind: 'compound' },
  { name: 'Banded Lateral Walk', muscleGroup: 'glutes', kind: 'isolation' },
  { name: 'Frog Pump', muscleGroup: 'glutes', kind: 'isolation' },
  { name: 'Reverse Hyperextension', muscleGroup: 'glutes', kind: 'isolation' },
  { name: 'Cable Hip Thrust', muscleGroup: 'glutes', kind: 'compound' },
  { name: 'Fire Hydrant', muscleGroup: 'glutes', kind: 'isolation' },
  { name: 'Clamshell', muscleGroup: 'glutes', kind: 'isolation' },
  { name: 'B-Stance Hip Thrust', muscleGroup: 'glutes', kind: 'compound' },

  // Calves
  { name: 'Standing Calf Raise', muscleGroup: 'calves', kind: 'isolation' },
  { name: 'Seated Calf Raise', muscleGroup: 'calves', kind: 'isolation' },
  { name: 'Leg Press Calf Raise', muscleGroup: 'calves', kind: 'isolation' },
  { name: 'Donkey Calf Raise', muscleGroup: 'calves', kind: 'isolation' },
  { name: 'Single-Leg Calf Raise', muscleGroup: 'calves', kind: 'isolation' },
  { name: 'Smith Machine Calf Raise', muscleGroup: 'calves', kind: 'isolation' },
  { name: 'Barbell Calf Raise', muscleGroup: 'calves', kind: 'isolation' },
  { name: 'Loaded Calf Walk', muscleGroup: 'calves', kind: 'isolation' },

  // Core
  { name: 'Plank', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Side Plank', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Crunch', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Bicycle Crunch', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Sit-up', muscleGroup: 'core', kind: 'compound' },
  { name: 'Hanging Leg Raise', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Cable Crunch', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Russian Twist', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Ab Wheel Rollout', muscleGroup: 'core', kind: 'compound' },
  { name: 'Pallof Press', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Mountain Climber', muscleGroup: 'core', kind: 'isolation' },
  { name: 'V-Up', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Flutter Kicks', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Dead Bug', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Cable Woodchopper', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Weighted Sit-up', muscleGroup: 'core', kind: 'compound' },
  { name: 'Toe Touch', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Reverse Crunch', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Hollow Body Hold', muscleGroup: 'core', kind: 'isolation' },
  { name: 'Weighted Russian Twist', muscleGroup: 'core', kind: 'isolation' },
]
